image:
  repository: sknnr/enshrouded-dedicated-server
  tag: v2.0.5

service:
  type: LoadBalancer
  externalIPs: []
  annotations: {}

resources:
  requests:
    memory: 6G
    cpu: 3

volumes:
  dataPVC:
    # -- Size of the persistent volume
    size: 50Gi
  storageClassName: "do-block-storage"

config:
  # -- Server name
  serverName: "Enshrouded Server"
  # -- Server password. If not set, password will be generated randomly.
  serverPassword: ""
  # -- Existing secret name for server password. Must contain key named "password". If set `serverPassword` will be ignored.
  serverPasswordExistingSecretName: ""
  gamePort: 15636
  queryPort: 15637
  # -- Number of server slots
  serverSlots: 16
  externalConfig: 0
